version: "3.7"

services:

  frontend:
    image: receiptanalysis/frontend
    restart: always
    container_name: "analysis-frontend"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - URL=receipt.modalstudio.com
      - VALIDATION=http
      - EMAIL=jaak.kytt@gmail.com
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - STAGING=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - analysis-front-logs:/logs
      - nginx-config:/config

volumes:
  analysis-front-logs:
  nginx-config:
